; Enable New Relic monitoring
extension = "newrelic.so"

newrelic.enabled = true
newrelic.monitor_mode = true
newrelic.logfile = "/var/log/newrelic/php_agent.log"
newrelic.loglevel = "info"

newrelic.daemon.address = "newrelic-php-daemon:31339"
newrelic.daemon.port = 31339
newrelic.daemon.docker = true

newrelic.browser_monitoring.auto_instrument = true
newrelic.transaction_tracer.enabled = true
newrelic.error_collector.enabled = true
newrelic.distributed_tracing_enabled = true

