; Enable New Relic monitoring
extension = "newrelic.so"

newrelic.enabled = true
newrelic.monitor_mode = true
newrelic.logfile = "/var/log/newrelic/php_agent.log"
newrelic.loglevel = "info"

# # ; Application name and license key will be populated from environment variables
# newrelic.appname = "${NEW_RELIC_APP_NAME}"
# newrelic.license = "${NEW_RELIC_LICENSE_KEY}"

newrelic.browser_monitoring.auto_instrument = true
newrelic.transaction_tracer.enabled = true
newrelic.error_collector.enabled = true
newrelic.distributed_tracing_enabled = true

