filebeat.inputs:
  - type: filestream
    id: local-logs
    enabled: true
    paths:
      - /var/log/laravel/*.log
    parsers:
      - ndjson:
          target: ""
          overwrite_keys: true
          add_error_key: true
    fields:
      app: prf-core
      environment: local
    fields_under_root: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "secret"

setup.kibana:
  host: "http://kibana:5601"

setup.template.name: "prf-logs"
setup.template.pattern: "prf-logs-*"

logging.level: info
logging.to_stderr: true

processors:
  - drop_fields:
      fields: ["agent", "ecs", "host", "input", "log"]
      ignore_missing: true
