<?php

return [
    'roles' => [
        'super admin' => [
            'viewAny users',
            'view users',
            'create users',
            'edit users',
            'delete users',
            'restore users',
            'forceDelete users',
            'view members',
            'create members',
            'edit members',
            'delete members',
            'restore members',
            'forceDelete members',
            'view mission subscriptions',
            'viewAny mission subscriptions',
            'create mission subscriptions',
            'edit mission subscriptions',
            'delete mission subscriptions',
            'restore mission subscriptions',
            'forceDelete mission subscriptions',
        ],

        'chairperson' => [
            'view users',
            'viewAny users',
            'create users',
            'edit users',
            'delete users',
            'restore users',
            'forceDelete users',
            'viewAny members',
            'view members',
            'create members',
            'edit members',
            'delete members',
            'restore members',
            'forceDelete members',
            'view mission subscriptions',
            'viewAny mission subscriptions',
            'create mission subscriptions',
            'edit mission subscriptions',
            'delete mission subscriptions',
            'restore mission subscriptions',
            'forceDelete mission subscriptions',

        ],

        'vice chairperson' => [
            'view users',
            'viewAny users',
            'create users',
            'edit users',
            'delete users',
            'restore users',
            'forceDelete users',
            'view members',
            'viewAny members',
            'create members',
            'edit members',
            'delete members',
            'restore members',
            'forceDelete members',
            'view mission subscriptions',
        ],

        'organising secretary' => [
            'view mission',
            'viewAny mission',
            'view members',
            'viewAny members',
        ],

        'mission coordinator' => [
            'create mission subscriptions',
            'view mission subscriptions',
            'viewAny mission subscriptions',
            'edit mission subscriptions',
            'delete mission subscriptions',
            'restore mission subscriptions',
            'forceDelete mission subscriptions',
            'view expenses',
            'viewAny expenses',
            'create expenses',
            'edit expenses',
            'delete expenses',
            'restore expenses',

        ],

        'vice mission coordinator' => [
            'view mission subscriptions',
            'viewAny mission subscriptions',
            'create mission subscriptions',
            'edit mission subscriptions',
            'delete mission subscriptions',
            'restore mission subscriptions',
            'forceDelete mission subscriptions',
            'view expenses',
            'viewAny expenses',
            'create expenses',
            'edit expenses',
            'delete expenses',
            'restore expenses',
        ],

        'treasurer' => [
            'view expenses',
            'viewAny expenses',
            'create expenses',
            'edit expenses',
            'delete expenses',
            'restore expenses',
            'forceDelete expenses',
        ],


        'member' => [
            'view mission',
            'viewAny mission',
            'edit profile',
            'subscribe to a mission',
            'unsubscribe to a mission',
        ],
    ],
];
