<?php

return [
    'roles' => [
        'super admin' => [
            'viewAny users',
            'view users',
            'create users',
            'edit users',
            'delete users',
            'restore users',
            'forceDelete users',

            'viewAny mission',
            'view mission',
            'create mission',
            'edit mission',
            'delete mission',
            'restore mission',
            'forceDelete mission',

            'viewAny mission type',
            'view mission type',
            'create mission type',
            'edit mission type',
            'delete mission type',
            'restore mission type',
            'forceDelete mission type',

            'viewAny class group',
            'view class group',
            'create class group',
            'edit class group',
            'delete class group',
            'restore class group',
            'forceDelete class group',

            'viewAny profession',
            'view profession',
            'create profession',
            'edit profession',
            'delete profession',
            'restore profession',
            'forceDelete profession',

            'viewAny school',
            'view school',
            'create school',
            'edit school',
            'delete school',
            'restore school',
            'forceDelete school',

            'viewAny school term',
            'view school term',
            'create school term',
            'edit school term',
            'delete school term',
            'restore school term',
            'forceDelete school term',

            'viewAny soul',
            'view soul',
            'create soul',
            'edit soul',
            'delete soul',
            'restore soul',
            'forceDelete soul',

            'viewAny church',
            'view church',
            'create church',
            'edit church',
            'delete church',
            'restore church',
            'forceDelete church',

            'viewAny marital status',
            'view marital status',
            'create marital status',
            'edit marital status',
            'delete marital status',
            'restore marital status',
            'forceDelete marital status',

            'viewAny department',
            'view department',
            'create department',
            'edit department',
            'delete department',
            'restore department',
            'forceDelete department',

            'viewAny contact type',
            'view contact type',
            'create contact type',
            'edit contact type',
            'delete contact type',
            'restore contact type',
            'forceDelete contact type',

            'viewAny mission subscription',
            'view mission subscription',
            'create mission subscription',
            'edit mission subscription',
            'delete mission subscription',
            'restore mission subscription',
            'forceDelete mission subscription',

            'viewAny gift',
            'view gift',
            'create gift',
            'edit gift',
            'delete gift',
            'restore gift',
            'forceDelete gift',

            'viewAny member',
            'view member',
            'create member',
            'edit member',
            'delete member',
            'restore member',
            'forceDelete member',

            'viewAny school contact',
            'view school contact',
            'create school contact',
            'edit school contact',
            'delete school contact',
            'restore school contact',
            'forceDelete school contact',

            'viewAny debrief note',
            'view debrief note',
            'create debrief note',
            'edit debrief note',
            'delete debrief note',
            'restore debrief note',
            'forceDelete debrief note',
        ],

        'chairperson' => [
            'viewAny users',
            'view users',
            'create users',
            'edit users',
            'delete users',
            'restore users',
            'forceDelete users',

            'viewAny mission',
            'view mission',
            'create mission',
            'edit mission',
            'delete mission',
            'restore mission',
            'forceDelete mission',

            'viewAny mission type',
            'view mission type',
            'create mission type',
            'edit mission type',
            'delete mission type',
            'restore mission type',
            'forceDelete mission type',

            'viewAny class group',
            'view class group',
            'create class group',
            'edit class group',
            'delete class group',
            'restore class group',
            'forceDelete class group',

            'viewAny profession',
            'view profession',
            'create profession',
            'edit profession',
            'delete profession',
            'restore profession',
            'forceDelete profession',

            'viewAny school',
            'view school',
            'create school',
            'edit school',
            'delete school',
            'restore school',
            'forceDelete school',

            'viewAny school term',
            'view school term',
            'create school term',
            'edit school term',
            'delete school term',
            'restore school term',
            'forceDelete school term',

            'viewAny soul',
            'view soul',
            'create soul',
            'edit soul',
            'delete soul',
            'restore soul',
            'forceDelete soul',

            'viewAny church',
            'view church',
            'create church',
            'edit church',
            'delete church',
            'restore church',
            'forceDelete church',

            'viewAny marital status',
            'view marital status',
            'create marital status',
            'edit marital status',
            'delete marital status',
            'restore marital status',
            'forceDelete marital status',

            'viewAny department',
            'view department',
            'create department',
            'edit department',
            'delete department',
            'restore department',
            'forceDelete department',

            'viewAny contact type',
            'view contact type',
            'create contact type',
            'edit contact type',
            'delete contact type',
            'restore contact type',
            'forceDelete contact type',

            'viewAny mission subscription',
            'view mission subscription',
            'create mission subscription',
            'edit mission subscription',
            'delete mission subscription',
            'restore mission subscription',
            'forceDelete mission subscription',

            'viewAny gift',
            'view gift',
            'create gift',
            'edit gift',
            'delete gift',
            'restore gift',
            'forceDelete gift',

            'viewAny member',
            'view member',
            'create member',
            'edit member',
            'delete member',
            'restore member',
            'forceDelete member',

            'viewAny school contact',
            'view school contact',

            'viewAny debrief note',
            'view debrief note',
        ],

        'vice chairperson' => [
            'viewAny users',
            'view users',
            'create users',
            'edit users',
            'delete users',
            'restore users',
            'forceDelete users',

            'viewAny mission',
            'view mission',
            'create mission',
            'edit mission',
            'delete mission',
            'restore mission',
            'forceDelete mission',

            'viewAny mission type',
            'view mission type',
            'create mission type',
            'edit mission type',
            'delete mission type',
            'restore mission type',
            'forceDelete mission type',

            'viewAny class group',
            'view class group',
            'create class group',
            'edit class group',
            'delete class group',
            'restore class group',
            'forceDelete class group',

            'viewAny profession',
            'view profession',
            'create profession',
            'edit profession',
            'delete profession',
            'restore profession',
            'forceDelete profession',

            'viewAny school',
            'view school',
            'create school',
            'edit school',
            'delete school',
            'restore school',
            'forceDelete school',

            'viewAny school term',
            'view school term',
            'create school term',
            'edit school term',
            'delete school erm',
            'restore school term',
            'forceDelete school erm',

            'viewAny soul',
            'view soul',
            'create soul',
            'edit soul',
            'delete soul',
            'restore soul',
            'forceDelete soul',

            'viewAny church',
            'view church',
            'create church',
            'edit church',
            'delete church',
            'restore church',
            'forceDelete church',

            'viewAny marital status',
            'view marital status',
            'create marital tatus',
            'edit marital status',
            'delete marital tatus',
            'restore marital status',
            'forceDelete marital tatus',

            'viewAny department',
            'view department',
            'create department',
            'edit department',
            'delete department',
            'restore department',
            'forceDelete department',

            'viewAny contact type',
            'view contact type',
            'create contact type',
            'edit contact type',
            'delete contact type',
            'restore contact type',
            'forceDelete contact type',

            'viewAny mission subscription',
            'view mission subscription',
            'create mission subscription',
            'edit mission subscription',
            'delete mission subscription',
            'restore mission subscription',
            'forceDelete mission subscription',

            'viewAny gift',
            'view gift',
            'create gift',
            'edit gift',
            'delete gift',
            'restore gift',
            'forceDelete gift',

            'viewAny member',
            'view member',
            'create member',
            'edit member',
            'delete member',
            'restore member',
            'forceDelete member',

            'viewAny school contact',
            'view school contact',

            'viewAny debrief note',
            'view debrief note',

        ],

        'organising secretary' => [
            'viewAny users',
            'view users',
            'create users',
            'edit users',
            'delete users',
            'restore users',
            'forceDelete users',

            'viewAny mission',
            'view mission',
            'viewAny mission type',
            'view mission type',

            'viewAny class group',
            'view class group',
            'create class group',
            'edit class group',
            'delete class group',
            'restore class group',
            'forceDelete class group',

            'viewAny profession',
            'view profession',
            'create profession',
            'edit profession',
            'delete profession',
            'restore profession',
            'forceDelete profession',

            'viewAny school',
            'view school',
            'create school',
            'edit school',
            'delete school',
            'restore school',
            'forceDelete school',

            'viewAny school term',
            'view school term',
            'create school term',
            'edit school term',
            'delete school term',
            'restore school term',
            'forceDelete school term',

            'viewAny church',
            'view church',
            'create church',
            'edit church',
            'delete church',
            'restore church',
            'forceDelete church',

            'viewAny marital status',
            'view marital status',
            'create marital status',
            'edit marital status',
            'delete marital status',
            'restore marital status',
            'forceDelete marital status',

            'viewAny department',
            'view department',
            'create department',
            'edit department',
            'delete department',
            'restore department',
            'forceDelete department',

            'viewAny contact type',
            'view contact type',
            'create contact type',
            'edit contact type',
            'delete contact type',
            'restore contact type',
            'forceDelete contact type',

            'viewAny gift',
            'view gift',
            'create gift',
            'edit gift',
            'delete gift',
            'restore gift',
            'forceDelete gift',

            'viewAny member',
            'view member',
            'create member',
            'edit member',
            'delete member',
            'restore member',
            'forceDelete member',

            'viewAny school contact',
            'view school contact',
            'create school contact',
            'edit school contact',
            'delete school contact',
            'restore school contact',
            'forceDelete school contact',

            'viewAny debrief note',
            'view debrief note',
        ],

        'mission coordinator' => [
            'viewAny users',
            'view users',
            'create users',
            'edit users',
            'delete users',
            'restore users',
            'forceDelete users',

            'viewAny mission',
            'view mission',
            'create mission',
            'edit mission',
            'delete mission',
            'restore mission',
            'forceDelete mission',

            'viewAny mission type',
            'view mission type',
            'create mission type',
            'edit mission type',
            'delete mission type',
            'restore mission type',
            'forceDelete mission type',

            'viewAny class group',
            'view class group',
            'create class group',
            'edit class group',
            'delete class group',
            'restore class group',
            'forceDelete class group',

            'viewAny profession',
            'view profession',
            'create profession',
            'edit profession',
            'delete profession',
            'restore profession',
            'forceDelete profession',

            'viewAny school',
            'view school',
            'create school',
            'edit school',
            'delete school',
            'restore school',
            'forceDelete school',

            'viewAny school term',
            'view school term',
            'create school term',
            'edit school term',
            'delete school term',
            'restore school term',
            'forceDelete school term',

            'viewAny soul',
            'view soul',
            'create soul',
            'edit soul',
            'delete soul',
            'restore soul',
            'forceDelete soul',

            'viewAny contact type',
            'view contact type',
            'create contact type',
            'edit contact type',
            'delete contact type',
            'restore contact type',
            'forceDelete contact type',

            'viewAny mission subscription',
            'view mission subscription',
            'create mission subscription',
            'edit mission subscription',
            'delete mission subscription',
            'restore mission subscription',
            'forceDelete mission subscription',

            'viewAny gift',
            'view gift',
            'create gift',
            'edit gift',
            'delete gift',
            'restore gift',
            'forceDelete gift',

            'viewAny member',
            'view member',

            'viewAny school contact',
            'view school contact',
            'create school contact',
            'edit school contact',
            'delete school contact',
            'restore school contact',
            'forceDelete school contact',

            'viewAny debrief note',
            'view debrief note',
            'create debrief note',
            'edit debrief note',
            'delete debrief note',
            'restore debrief note',
            'forceDelete debrief note',
        ],

        'vice mission coordinator' => [
            'viewAny users',
            'view users',
            'create users',
            'edit users',
            'delete users',
            'restore users',
            'forceDelete users',

            'viewAny mission',
            'view mission',
            'create mission',
            'edit mission',
            'delete mission',
            'restore mission',
            'forceDelete mission',

            'viewAny mission type',
            'view mission type',
            'create mission type',
            'edit mission type',
            'delete mission type',
            'restore mission type',
            'forceDelete mission type',

            'viewAny class group',
            'view class group',
            'create class group',
            'edit class group',
            'delete class group',
            'restore class group',
            'forceDelete class group',

            'viewAny profession',
            'view profession',
            'create profession',
            'edit profession',
            'delete profession',
            'restore profession',
            'forceDelete profession',

            'viewAny school',
            'view school',
            'create school',
            'edit school',
            'delete school',
            'restore school',
            'forceDelete school',

            'viewAny school term',
            'view school term',
            'create school term',
            'edit school term',
            'delete school term',
            'restore school term',
            'forceDelete school term',

            'viewAny soul',
            'view soul',
            'create soul',
            'edit soul',
            'delete soul',
            'restore soul',
            'forceDelete soul',

            'viewAny contact type',
            'view contact type',
            'create contact type',
            'edit contact type',
            'delete contact type',
            'restore contact type',
            'forceDelete contact type',

            'viewAny mission subscription',
            'view mission subscription',
            'create mission subscription',
            'edit mission subscription',
            'delete mission subscription',
            'restore mission subscription',
            'forceDelete mission subscription',

            'viewAny gift',
            'view gift',
            'create gift',
            'edit gift',
            'delete gift',
            'restore gift',
            'forceDelete gift',

            'viewAny member',
            'view member',

            'viewAny school contact',
            'view school contact',
            'create school contact',
            'edit school contact',
            'delete school contact',
            'restore school contact',
            'forceDelete school contact',

            'viewAny debrief note',
            'view debrief note',
            'create debrief note',
            'edit debrief note',
            'delete debrief note',
            'restore debrief note',
            'forceDelete debrief note',
        ],

        'treasurer' => [
            'view expenses',
            'viewAny mission type',
            'viewAny member',
            'view mission',
            'viewAny expenses',
            'create expenses',
            'edit expenses',
            'delete expenses',
            'restore expenses',
            'forceDelete expenses',
        ],

        'member' => [],

    ],
];
