<?php

return [
    'roles' => [
        'super admin' => [
            'viewAny users',
            'view users',
            'create users',
            'edit users',
            'delete users',
            'restore users',
            'forceDelete users',

            'viewAny mission',
            'view mission',
            'create mission',
            'edit mission',
            'delete mission',
            'restore mission',
            'forceDelete mission',

            'viewAny mission_type',
            'view mission_type',
            'create mission_type',
            'edit mission_type',
            'delete mission_type',
            'restore mission_type',
            'forceDelete mission_type',

            'viewAny class_group',
            'view class_group',
            'create class_group',
            'edit class_group',
            'delete class_group',
            'restore class_group',
            'forceDelete class_group',

            'viewAny profession',
            'view profession',
            'create profession',
            'edit profession',
            'delete profession',
            'restore profession',
            'forceDelete profession',

            'viewAny school',
            'view school',
            'create school',
            'edit school',
            'delete school',
            'restore school',
            'forceDelete school',

            'viewAny school_term',
            'view school_term',
            'create school_term',
            'edit school_term',
            'delete school_term',
            'restore school_term',
            'forceDelete school_term',

            'viewAny soul',
            'view soul',
            'create soul',
            'edit soul',
            'delete soul',
            'restore soul',
            'forceDelete soul',

            'viewAny church',
            'view church',
            'create church',
            'edit church',
            'delete church',
            'restore church',
            'forceDelete church',


            'viewAny marital_status',
            'view marital_status',
            'create marital_status',
            'edit marital_status',
            'delete marital_status',
            'restore marital_status',
            'forceDelete marital_status',

            'viewAny department',
            'view department',
            'create department',
            'edit department',
            'delete department',
            'restore department',
            'forceDelete department',

            'viewAny contact_type',
            'view contact_type',
            'create contact_type',
            'edit contact_type',
            'delete contact_type',
            'restore contact_type',
            'forceDelete contact_type',


            'viewAny mission subscriptions',
            'view mission subscriptions',
            'create mission subscriptions',
            'edit mission subscriptions',
            'delete mission subscriptions',
            'restore mission subscriptions',
            'forceDelete mission subscriptions',

            'viewAny gift',
            'view gift',
            'create gift',
            'edit gift',
            'delete gift',
            'restore gift',
            'forceDelete gift',

            'viewAny member',
            'view member',
            'create member',
            'edit member',
            'delete member',
            'restore member',
            'forceDelete member',


        ],

        'chairperson' => [
            'viewAny users',
            'view users',
            'create users',
            'edit users',
            'delete users',
            'restore users',
            'forceDelete users',

            'viewAny mission',
            'view mission',
            'create mission',
            'edit mission',
            'delete mission',
            'restore mission',
            'forceDelete mission',

            'viewAny mission_type',
            'view mission_type',
            'create mission_type',
            'edit mission_type',
            'delete mission_type',
            'restore mission_type',
            'forceDelete mission_type',

            'viewAny class_group',
            'view class_group',
            'create class_group',
            'edit class_group',
            'delete class_group',
            'restore class_group',
            'forceDelete class_group',

            'viewAny profession',
            'view profession',
            'create profession',
            'edit profession',
            'delete profession',
            'restore profession',
            'forceDelete profession',

            'viewAny school',
            'view school',
            'create school',
            'edit school',
            'delete school',
            'restore school',
            'forceDelete school',

            'viewAny school_term',
            'view school_term',
            'create school_term',
            'edit school_term',
            'delete school_term',
            'restore school_term',
            'forceDelete school_term',

            'viewAny soul',
            'view soul',
            'create soul',
            'edit soul',
            'delete soul',
            'restore soul',
            'forceDelete soul',

            'viewAny church',
            'view church',
            'create church',
            'edit church',
            'delete church',
            'restore church',
            'forceDelete church',


            'viewAny marital_status',
            'view marital_status',
            'create marital_status',
            'edit marital_status',
            'delete marital_status',
            'restore marital_status',
            'forceDelete marital_status',

            'viewAny department',
            'view department',
            'create department',
            'edit department',
            'delete department',
            'restore department',
            'forceDelete department',

            'viewAny contact_type',
            'view contact_type',
            'create contact_type',
            'edit contact_type',
            'delete contact_type',
            'restore contact_type',
            'forceDelete contact_type',


            'viewAny mission subscriptions',
            'view mission subscriptions',
            'create mission subscriptions',
            'edit mission subscriptions',
            'delete mission subscriptions',
            'restore mission subscriptions',
            'forceDelete mission subscriptions',

            'viewAny gift',
            'view gift',
            'create gift',
            'edit gift',
            'delete gift',
            'restore gift',
            'forceDelete gift',

            'viewAny member',
            'view member',
            'create member',
            'edit member',
            'delete member',
            'restore member',
            'forceDelete member',

        ],

        'vice chairperson' => [
            'viewAny users',
            'view users',
            'create users',
            'edit users',
            'delete users',
            'restore users',
            'forceDelete users',

            'viewAny mission',
            'view mission',
            'create mission',
            'edit mission',
            'delete mission',
            'restore mission',
            'forceDelete mission',

            'viewAny mission_type',
            'view mission_type',
            'create mission_type',
            'edit mission_type',
            'delete mission_type',
            'restore mission_type',
            'forceDelete mission_type',

            'viewAny class_group',
            'view class_group',
            'create class_group',
            'edit class_group',
            'delete class_group',
            'restore class_group',
            'forceDelete class_group',

            'viewAny profession',
            'view profession',
            'create profession',
            'edit profession',
            'delete profession',
            'restore profession',
            'forceDelete profession',

            'viewAny school',
            'view school',
            'create school',
            'edit school',
            'delete school',
            'restore school',
            'forceDelete school',

            'viewAny school_term',
            'view school_term',
            'create school_term',
            'edit school_term',
            'delete school_term',
            'restore school_term',
            'forceDelete school_term',

            'viewAny soul',
            'view soul',
            'create soul',
            'edit soul',
            'delete soul',
            'restore soul',
            'forceDelete soul',

            'viewAny church',
            'view church',
            'create church',
            'edit church',
            'delete church',
            'restore church',
            'forceDelete church',


            'viewAny marital_status',
            'view marital_status',
            'create marital_status',
            'edit marital_status',
            'delete marital_status',
            'restore marital_status',
            'forceDelete marital_status',

            'viewAny department',
            'view department',
            'create department',
            'edit department',
            'delete department',
            'restore department',
            'forceDelete department',

            'viewAny contact_type',
            'view contact_type',
            'create contact_type',
            'edit contact_type',
            'delete contact_type',
            'restore contact_type',
            'forceDelete contact_type',


            'viewAny mission subscriptions',
            'view mission subscriptions',
            'create mission subscriptions',
            'edit mission subscriptions',
            'delete mission subscriptions',
            'restore mission subscriptions',
            'forceDelete mission subscriptions',

            'viewAny gift',
            'view gift',
            'create gift',
            'edit gift',
            'delete gift',
            'restore gift',
            'forceDelete gift',

            'viewAny member',
            'view member',
            'create member',
            'edit member',
            'delete member',
            'restore member',
            'forceDelete member',

        ],

        'organising secretary' => [
            'viewAny users',
            'view users',
            'create users',
            'edit users',
            'delete users',
            'restore users',
            'forceDelete users',

            'viewAny mission',
            'view mission',
            'viewAny mission_type',
            'view mission_type',


            'viewAny class_group',
            'view class_group',
            'create class_group',
            'edit class_group',
            'delete class_group',
            'restore class_group',
            'forceDelete class_group',

            'viewAny profession',
            'view profession',
            'create profession',
            'edit profession',
            'delete profession',
            'restore profession',
            'forceDelete profession',

            'viewAny school',
            'view school',
            'create school',
            'edit school',
            'delete school',
            'restore school',
            'forceDelete school',

            'viewAny school_term',
            'view school_term',
            'create school_term',
            'edit school_term',
            'delete school_term',
            'restore school_term',
            'forceDelete school_term',



            'viewAny church',
            'view church',
            'create church',
            'edit church',
            'delete church',
            'restore church',
            'forceDelete church',


            'viewAny marital_status',
            'view marital_status',
            'create marital_status',
            'edit marital_status',
            'delete marital_status',
            'restore marital_status',
            'forceDelete marital_status',

            'viewAny department',
            'view department',
            'create department',
            'edit department',
            'delete department',
            'restore department',
            'forceDelete department',

            'viewAny contact_type',
            'view contact_type',
            'create contact_type',
            'edit contact_type',
            'delete contact_type',
            'restore contact_type',
            'forceDelete contact_type',


            'viewAny gift',
            'view gift',
            'create gift',
            'edit gift',
            'delete gift',
            'restore gift',
            'forceDelete gift',

            'viewAny member',
            'view member',
            'create member',
            'edit member',
            'delete member',
            'restore member',
            'forceDelete member',

        ],

        'mission coordinator' => [
            'viewAny users',
            'view users',
            'create users',
            'edit users',
            'delete users',
            'restore users',
            'forceDelete users',

            'viewAny mission',
            'view mission',
            'create mission',
            'edit mission',
            'delete mission',
            'restore mission',
            'forceDelete mission',

            'viewAny mission_type',
            'view mission_type',
            'create mission_type',
            'edit mission_type',
            'delete mission_type',
            'restore mission_type',
            'forceDelete mission_type',

            'viewAny class_group',
            'view class_group',
            'create class_group',
            'edit class_group',
            'delete class_group',
            'restore class_group',
            'forceDelete class_group',

            'viewAny profession',
            'view profession',
            'create profession',
            'edit profession',
            'delete profession',
            'restore profession',
            'forceDelete profession',

            'viewAny school',
            'view school',
            'create school',
            'edit school',
            'delete school',
            'restore school',
            'forceDelete school',

            'viewAny school_term',
            'view school_term',
            'create school_term',
            'edit school_term',
            'delete school_term',
            'restore school_term',
            'forceDelete school_term',

            'viewAny soul',
            'view soul',
            'create soul',
            'edit soul',
            'delete soul',
            'restore soul',
            'forceDelete soul',


            'viewAny contact_type',
            'view contact_type',
            'create contact_type',
            'edit contact_type',
            'delete contact_type',
            'restore contact_type',
            'forceDelete contact_type',


            'viewAny mission subscriptions',
            'view mission subscriptions',
            'create mission subscriptions',
            'edit mission subscriptions',
            'delete mission subscriptions',
            'restore mission subscriptions',
            'forceDelete mission subscriptions',

            'viewAny gift',
            'view gift',
            'create gift',
            'edit gift',
            'delete gift',
            'restore gift',
            'forceDelete gift',

            'viewAny member',
            'view member',
        ],

        'vice mission coordinator' => [
            'viewAny users',
            'view users',
            'create users',
            'edit users',
            'delete users',
            'restore users',
            'forceDelete users',

            'viewAny mission',
            'view mission',
            'create mission',
            'edit mission',
            'delete mission',
            'restore mission',
            'forceDelete mission',

            'viewAny mission_type',
            'view mission_type',
            'create mission_type',
            'edit mission_type',
            'delete mission_type',
            'restore mission_type',
            'forceDelete mission_type',

            'viewAny class_group',
            'view class_group',
            'create class_group',
            'edit class_group',
            'delete class_group',
            'restore class_group',
            'forceDelete class_group',

            'viewAny profession',
            'view profession',
            'create profession',
            'edit profession',
            'delete profession',
            'restore profession',
            'forceDelete profession',

            'viewAny school',
            'view school',
            'create school',
            'edit school',
            'delete school',
            'restore school',
            'forceDelete school',

            'viewAny school_term',
            'view school_term',
            'create school_term',
            'edit school_term',
            'delete school_term',
            'restore school_term',
            'forceDelete school_term',

            'viewAny soul',
            'view soul',
            'create soul',
            'edit soul',
            'delete soul',
            'restore soul',
            'forceDelete soul',


            'viewAny contact_type',
            'view contact_type',
            'create contact_type',
            'edit contact_type',
            'delete contact_type',
            'restore contact_type',
            'forceDelete contact_type',


            'viewAny mission subscriptions',
            'view mission subscriptions',
            'create mission subscriptions',
            'edit mission subscriptions',
            'delete mission subscriptions',
            'restore mission subscriptions',
            'forceDelete mission subscriptions',

            'viewAny gift',
            'view gift',
            'create gift',
            'edit gift',
            'delete gift',
            'restore gift',
            'forceDelete gift',

            'viewAny member',
            'view member',
        ],

        'treasurer' => [
            'view expenses',
            'viewAny mission_type',
            'viewAny member',
            'view mission',
            'viewAny expenses',
            'create expenses',
            'edit expenses',
            'delete expenses',
            'restore expenses',
            'forceDelete expenses',
        ],

        // 'member' => [
        //     'view mission',
        //     'viewAny mission',
        //     'edit profile',
        //     'subscribe to a mission',
        //     'unsubscribe to a mission',
        // ],
    ],
];
