name: Production Deployment

on:
  release:
    types: [published]

jobs:
  build_and_deploy:
    name: Production build and deploy
    runs-on: ubuntu-latest
    timeout-minutes: 40

    env:
      DOCKER_BUILDKIT: 1
      DEBUG: on
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
      REVERB_APP_ID: ${{ secrets.REVERB_APP_ID }}
      REVERB_APP_KEY: ${{ secrets.REVERB_APP_KEY }}
      REVERB_APP_SECRET: ${{ secrets.REVERB_APP_SECRET }}
      REVERB_HOST: ${{ secrets.REVERB_HOST }}
      VITE_REVERB_APP_KEY: ${{ secrets.VITE_REVERB_APP_KEY }}
      VITE_REVERB_HOST: ${{ secrets.VITE_REVERB_HOST }}
      WEATHER_API_URL: ${{ secrets.WEATHER_API_URL }}
      WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      DRAGONFLY_PASSWORD: ${{ secrets.DRAGONFLY_PASSWORD }}
      APP_KEY: ${{ secrets.APP_KEY }}
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      AZURE_STORAGE_CONTAINER: ${{ secrets.AZURE_STORAGE_CONTAINER }}
      AZURE_SPEECH_SUBSCRIPTION_KEY: ${{ secrets.AZURE_SPEECH_SUBSCRIPTION_KEY }}
      MAIL_HOST: ${{ secrets.MAIL_HOST }}
      MAIL_PORT: ${{ secrets.MAIL_PORT }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      MAIL_ENCRYPTION: ${{ secrets.MAIL_ENCRYPTION }}
      MAIL_FROM_ADDRESS: ${{ secrets.MAIL_FROM_ADDRESS }}
      PAYSTACK_PUBLIC_KEY: ${{ secrets.PAYSTACK_PUBLIC_KEY }}
      PAYSTACK_SECRET_KEY: ${{ secrets.PAYSTACK_SECRET_KEY }}
      AFRICAS_TALKING_USERNAME: ${{ secrets.AFRICAS_TALKING_USERNAME }}
      AFRICAS_TALKING_API_KEY: ${{ secrets.AFRICAS_TALKING_API_KEY }}
      NEW_RELIC_APP_NAME: ${{ secrets.NEW_RELIC_APP_NAME }}
      NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
      NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
      NEW_RELIC_APP_ID: ${{ secrets.NEW_RELIC_APP_ID }}
      ADVANTA_BASE_URL: ${{ secrets.ADVANTA_BASE_URL }}
      ADVANTA_PARTNER_ID: ${{ secrets.ADVANTA_PARTNER_ID }}
      ADVANTA_API_KEY: ${{ secrets.ADVANTA_API_KEY }}
      ADVANTA_SHORT_CODE: ${{ secrets.ADVANTA_SHORT_CODE }}
      MB_DB_HOST: ${{ secrets.DB_HOST }}
      MB_DB_USER: ${{ secrets.DB_USERNAME }}
      MB_DB_PASS: ${{ secrets.DB_PASSWORD }}
      MB_DB_DBNAME: ${{ secrets.MB_DB_DBNAME }} 
      EMAIL_HOST: ${{ secrets.MAIL_HOST }}
      EMAIL_PORT: ${{ secrets.MAIL_PORT }}
      EMAIL_USER: ${{ secrets.MAIL_USERNAME }}
      EMAIL_PASS:  ${{ secrets.MAIL_PASSWORD }}
      DATABASE_URL: postgresql://${{ secrets.DB_USERNAME }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/postiz
      REDIS_URL: redis://:${{ secrets.DRAGONFLY_PASSWORD }}@${{ secrets.REDIS_HOST }}:${{ secrets.REDIS_PORT }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_ACCESS_KEY: ${{ secrets.CLOUDFLARE_ACCESS_KEY }}
      CLOUDFLARE_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}
      CLOUDFLARE_BUCKETNAME: ${{ secrets.CLOUDFLARE_BUCKETNAME }}
      CLOUDFLARE_REGION: ${{ secrets.CLOUDFLARE_REGION }}
      CLOUDFLARE_BUCKET_URL: ${{ secrets.CLOUDFLARE_BUCKET_URL }}
      KUTT_API_KEY: ${{ secrets.KUTT_API_KEY }}
      DB_PORT: ${{ secrets.DB_PORT }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Firebase credentials file
        run: |
          mkdir -p storage/app
          echo "$GOOGLE_APPLICATION_CREDENTIALS" > storage/app/firebase-auth.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      
      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0

      - name: Cache Kamal gems
        uses: actions/cache@v4
        with:
          path: ~/.gem
          key: ${{ runner.os }}-gems-kamal-${{ hashFiles('**/deploy.yml') }}
          restore-keys: |
            ${{ runner.os }}-gems-kamal-

      - name: Install dependencies
        run: |
          gem install specific_install
          gem specific_install https://github.com/basecamp/kamal.git

      - name: Validate Kamal configuration
        run: |
          kamal config -c manifests/kamal/deploy.yml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:master

      - name: Create .env files
        run: |
          # Create secrets directory if it doesn't exist
          mkdir -p .kamal
          
          # Create secrets file with proper permissions
          touch .kamal/secrets
          chmod 600 .kamal/secrets
          
          # Populate secrets file
          echo "KAMAL_REGISTRY_PASSWORD=$KAMAL_REGISTRY_PASSWORD" >> .kamal/secrets
          echo "REDIS_HOST=$REDIS_HOST" >> .kamal/secrets
          echo "REDIS_PASSWORD=$REDIS_PASSWORD" >> .kamal/secrets
          echo "REDIS_PORT=$REDIS_PORT" >> .kamal/secrets
          echo "DB_HOST=$DB_HOST" >> .kamal/secrets
          echo "DB_DATABASE=$DB_DATABASE" >> .kamal/secrets
          echo "DB_USERNAME=$DB_USERNAME" >> .kamal/secrets
          echo "DB_PASSWORD=$DB_PASSWORD" >> .kamal/secrets
          echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID" >> .kamal/secrets
          echo "GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET" >> .kamal/secrets
          echo "GOOGLE_REDIRECT_URI=$GOOGLE_REDIRECT_URI" >> .kamal/secrets
          echo "REVERB_APP_ID=$REVERB_APP_ID" >> .kamal/secrets
          echo "REVERB_APP_KEY=$REVERB_APP_KEY" >> .kamal/secrets
          echo "REVERB_APP_SECRET=$REVERB_APP_SECRET" >> .kamal/secrets
          echo "REVERB_HOST=$REVERB_HOST" >> .kamal/secrets
          echo "VITE_REVERB_APP_KEY=$VITE_REVERB_APP_KEY" >> .kamal/secrets
          echo "VITE_REVERB_HOST=$VITE_REVERB_HOST" >> .kamal/secrets
          echo "WEATHER_API_URL=$WEATHER_API_URL" >> .kamal/secrets
          echo "WEATHER_API_KEY=$WEATHER_API_KEY" >> .kamal/secrets
          echo "GEMINI_API_KEY=$GEMINI_API_KEY" >> .kamal/secrets
          echo "GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY" >> .kamal/secrets
          echo "POSTGRES_USER=$POSTGRES_USER" >> .kamal/secrets
          echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .kamal/secrets
          echo "POSTGRES_DB=$POSTGRES_DB" >> .kamal/secrets
          echo "DRAGONFLY_PASSWORD=$DRAGONFLY_PASSWORD" >> .kamal/secrets
          echo "APP_KEY=$APP_KEY" >> .kamal/secrets
          echo "AZURE_STORAGE_CONNECTION_STRING=$AZURE_STORAGE_CONNECTION_STRING" >> .kamal/secrets
          echo "AZURE_STORAGE_CONTAINER=$AZURE_STORAGE_CONTAINER" >> .kamal/secrets
          echo "AZURE_SPEECH_SUBSCRIPTION_KEY=$AZURE_SPEECH_SUBSCRIPTION_KEY" >>.kamal/secrets
          echo "MAIL_HOST=$MAIL_HOST" >>.kamal/secrets
          echo "MAIL_PORT=$MAIL_PORT" >>.kamal/secrets
          echo "MAIL_USERNAME=$MAIL_USERNAME" >>.kamal/secrets
          echo "MAIL_PASSWORD=$MAIL_PASSWORD" >>.kamal/secrets
          echo "MAIL_ENCRYPTION=$MAIL_ENCRYPTION" >>.kamal/secrets
          echo "MAIL_FROM_ADDRESS=$MAIL_FROM_ADDRESS" >>.kamal/secrets
          echo "PAYSTACK_PUBLIC_KEY=$PAYSTACK_PUBLIC_KEY" >>.kamal/secrets
          echo "PAYSTACK_SECRET_KEY=$PAYSTACK_SECRET_KEY" >>.kamal/secrets
          echo "AFRICAS_TALKING_USERNAME=$AFRICAS_TALKING_USERNAME" >>.kamal/secrets
          echo "AFRICAS_TALKING_API_KEY=$AFRICAS_TALKING_API_KEY" >>.kamal/secrets
          echo "NEW_RELIC_APP_NAME=$NEW_RELIC_APP_NAME" >>.kamal/secrets
          echo "NEW_RELIC_LICENSE_KEY=$NEW_RELIC_LICENSE_KEY" >>.kamal/secrets
          echo "NEW_RELIC_API_KEY=$NEW_RELIC_API_KEY" >>.kamal/secrets
          echo "NEW_RELIC_APP_ID=$NEW_RELIC_APP_ID" >>.kamal/secrets
          echo "ADVANTA_BASE_URL=$ADVANTA_BASE_URL" >>.kamal/secrets
          echo "ADVANTA_PARTNER_ID=$ADVANTA_PARTNER_ID" >>.kamal/secrets
          echo "ADVANTA_API_KEY=$ADVANTA_API_KEY" >>.kamal/secrets
          echo "ADVANTA_SHORT_CODE=$ADVANTA_SHORT_CODE" >>.kamal/secrets
          echo "MB_DB_HOST=$MB_DB_HOST" >>.kamal/secrets
          echo "MB_DB_USER=$MB_DB_USER" >>.kamal/secrets
          echo "MB_DB_PASS=$MB_DB_PASS" >>.kamal/secrets
          echo "MB_DB_DBNAME=$MB_DB_DBNAME" >>.kamal/secrets
          echo "EMAIL_HOST=$EMAIL_HOST" >> .kamal/secrets
          echo "EMAIL_PORT=$EMAIL_PORT" >> .kamal/secrets
          echo "EMAIL_USER=$EMAIL_USER" >> .kamal/secrets
          echo "EMAIL_PASS=$EMAIL_PASS" >> .kamal/secrets
          echo "DATABASE_URL=$DATABASE_URL" >> .kamal/secrets
          echo "REDIS_URL=$REDIS_URL" >> .kamal/secrets
          echo "CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID" >> .kamal/secrets
          echo "CLOUDFLARE_ACCESS_KEY=$CLOUDFLARE_ACCESS_KEY" >> .kamal/secrets
          echo "CLOUDFLARE_SECRET_ACCESS_KEY=$CLOUDFLARE_SECRET_ACCESS_KEY" >> .kamal/secrets
          echo "CLOUDFLARE_BUCKETNAME=$CLOUDFLARE_BUCKETNAME" >> .kamal/secrets
          echo "CLOUDFLARE_REGION=$CLOUDFLARE_REGION" >> .kamal/secrets
          echo "CLOUDFLARE_BUCKET_URL=$CLOUDFLARE_BUCKET_URL" >> .kamal/secrets
          echo "DB_USER=$DB_USERNAME" >> .kamal/secrets
          echo "MAIL_USER=$MAIL_USERNAME" >> .kamal/secrets
          echo "DB_PORT=$DB_PORT" >> .kamal/secrets
          echo "POSTIZ_OAUTH_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET" >> .kamal/secrets
          echo "POSTIZ_OAUTH_CLIENT_ID=$GOOGLE_CLIENT_ID" >> .kamal/secrets
          echo "KUTT_API_KEY=$KUTT_API_KEY" >> .kamal/secrets
          echo "EMAIL_FROM_ADDRESS=$MAIL_FROM_ADDRESS" >> .kamal/secrets

      - name: Deploy accessories & the app
        id: deploy
        run: |
          set -e
          echo "::group::Releasing deployment lock"
          kamal lock release -c manifests/kamal/deploy.yml
          echo "::endgroup::"
          
          echo "::group::Booting accessories"
          kamal accessory boot dragonfly -c manifests/kamal/deploy.yml
          kamal accessory boot postgres -c manifests/kamal/deploy.yml
          kamal accessory boot metabase -c manifests/kamal/deploy.yml
          echo "::endgroup::"
          
          echo "::group::Deploying application"
          kamal deploy -c manifests/kamal/deploy.yml -v
          echo "::endgroup::"

      # - name: Reconfigure the proxy
      #   run: |
      #     kamal lock release -c manifests/kamal/deploy.yml
      #     kamal proxy reboot -y --rolling -c manifests/kamal/deploy.yml
      #     kamal deploy -c manifests/kamal/deploy.yml -v

      - name: Notify deployment failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: https://hooks.slack.com/services/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
          SLACK_MESSAGE: "❌ Production deployment failed for release ${{ github.event.release.tag_name }}. Check the logs for details."
          SLACK_COLOR: "danger"
          SLACK_USERNAME: "GitHub Actions"
          SLACK_TITLE: "Deployment Failed"
