name: Staging Deployment

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    timeout-minutes: 40

    env:
      DOCKER_BUILDKIT: 1
      DEBUG: on
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
      REVERB_APP_ID: ${{ secrets.REVERB_APP_ID }}
      REVERB_APP_KEY: ${{ secrets.REVERB_APP_KEY }}
      REVERB_APP_SECRET: ${{ secrets.REVERB_APP_SECRET }}
      REVERB_HOST: ${{ secrets.REVERB_HOST }}
      VITE_REVERB_APP_KEY: ${{ secrets.VITE_REVERB_APP_KEY }}
      VITE_REVERB_HOST: ${{ secrets.VITE_REVERB_HOST }}
      ONESIGNAL_APP_ID: ${{ secrets.ONESIGNAL_APP_ID }}
      ONESIGNAL_REST_API_KEY: ${{ secrets.ONESIGNAL_REST_API_KEY }}
      WEATHER_API_URL: ${{ secrets.WEATHER_API_URL }}
      WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      DRAGONFLY_PASSWORD: ${{ secrets.DRAGONFLY_PASSWORD }}
      APP_KEY: ${{ secrets.APP_KEY }}
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      AZURE_STORAGE_CONTAINER: ${{ secrets.AZURE_STORAGE_CONTAINER }}
      PESAPAL_NOTIFICATION_ID: ${{ secrets.PESAPAL_NOTIFICATION_ID }}
      AZURE_SPEECH_SUBSCRIPTION_KEY: ${{ secrets.AZURE_SPEECH_SUBSCRIPTION_KEY }}
      MAIL_HOST: ${{ secrets.MAIL_HOST }}
      MAIL_PORT: ${{ secrets.MAIL_PORT }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      MAIL_ENCRYPTION: ${{ secrets.MAIL_ENCRYPTION }}
      MAIL_FROM_ADDRESS: ${{ secrets.MAIL_FROM_ADDRESS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install specific_install
          gem specific_install https://github.com/basecamp/kamal.git

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:master

      - name: Create .env files
        run: |
          echo "KAMAL_REGISTRY_PASSWORD=$KAMAL_REGISTRY_PASSWORD" >> .kamal/secrets
          echo "REDIS_HOST=$REDIS_HOST" >> .kamal/secrets
          echo "REDIS_PASSWORD=$REDIS_PASSWORD" >> .kamal/secrets
          echo "REDIS_PORT=$REDIS_PORT" >> .kamal/secrets
          echo "DB_HOST=$DB_HOST" >> .kamal/secrets
          echo "DB_DATABASE=$DB_DATABASE" >> .kamal/secrets
          echo "DB_USERNAME=$DB_USERNAME" >> .kamal/secrets
          echo "DB_PASSWORD=$DB_PASSWORD" >> .kamal/secrets
          echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID" >> .kamal/secrets
          echo "GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET" >> .kamal/secrets
          echo "GOOGLE_REDIRECT_URI=$GOOGLE_REDIRECT_URI" >> .kamal/secrets
          echo "REVERB_APP_ID=$REVERB_APP_ID" >> .kamal/secrets
          echo "REVERB_APP_KEY=$REVERB_APP_KEY" >> .kamal/secrets
          echo "REVERB_APP_SECRET=$REVERB_APP_SECRET" >> .kamal/secrets
          echo "REVERB_HOST=$REVERB_HOST" >> .kamal/secrets
          echo "VITE_REVERB_APP_KEY=$VITE_REVERB_APP_KEY" >> .kamal/secrets
          echo "VITE_REVERB_HOST=$VITE_REVERB_HOST" >> .kamal/secrets
          echo "ONESIGNAL_APP_ID=$ONESIGNAL_APP_ID" >> .kamal/secrets
          echo "ONESIGNAL_REST_API_KEY=$ONESIGNAL_REST_API_KEY" >> .kamal/secrets
          echo "WEATHER_API_URL=$WEATHER_API_URL" >> .kamal/secrets
          echo "WEATHER_API_KEY=$WEATHER_API_KEY" >> .kamal/secrets
          echo "GEMINI_API_KEY=$GEMINI_API_KEY" >> .kamal/secrets
          echo "GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY" >> .kamal/secrets
          echo "POSTGRES_USER=$POSTGRES_USER" >> .kamal/secrets
          echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .kamal/secrets
          echo "POSTGRES_DB=$POSTGRES_DB" >> .kamal/secrets
          echo "DRAGONFLY_PASSWORD=$DRAGONFLY_PASSWORD" >> .kamal/secrets
          echo "APP_KEY=$APP_KEY" >> .kamal/secrets
          echo "AZURE_STORAGE_CONNECTION_STRING=$AZURE_STORAGE_CONNECTION_STRING" >> .kamal/secrets
          echo "AZURE_STORAGE_CONTAINER=$AZURE_STORAGE_CONTAINER" >> .kamal/secrets
          echo "PESAPAL_NOTIFICATION_ID=$PESAPAL_NOTIFICATION_ID" >>.kamal/secrets
          echo "AZURE_SPEECH_SUBSCRIPTION_KEY=$AZURE_SPEECH_SUBSCRIPTION_KEY" >>.kamal/secrets
          echo "MAIL_HOST=$MAIL_HOST" >>.kamal/secrets
          echo "MAIL_PORT=$MAIL_PORT" >>.kamal/secrets
          echo "MAIL_USERNAME=$MAIL_USERNAME" >>.kamal/secrets
          echo "MAIL_PASSWORD=$MAIL_PASSWORD" >>.kamal/secrets
          echo "MAIL_ENCRYPTION=$MAIL_ENCRYPTION" >>.kamal/secrets
          echo "MAIL_FROM_ADDRESS=$MAIL_FROM_ADDRESS" >>.kamal/secrets
          

      # - name: Run deploy command (First run)
      #   run: |
      #     kamal lock release
      #     kamal accessory boot all
      #     kamal deploy -v

      - name: Run deploy command
        run: |
          kamal lock release
          kamal deploy -v

      - name: Status
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: https://hooks.slack.com/services/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
